import {
  USStateValue,
  USTerritoryValue,
  NativeAmericanValue,
  CanadianValue,
  MexicanValue,
} from '../data';

export const getSelectedScore = (value: string) => {
  switch (value) {
    case USStateValue.California:
    case USStateValue.Florida:
    case USStateValue.NewYork:
    case USStateValue.Texas:
      return 1;
    case USStateValue.Georgia:
    case USStateValue.Illinois:
    case USStateValue.Michigan:
    case USStateValue.NorthCarolina:
    case USStateValue.Ohio:
    case USStateValue.Pennsylvania:
      return 2;
    case USStateValue.Alabama:
    case USStateValue.Arizona:
    case USStateValue.Colorado:
    case USStateValue.Indiana:
    case USStateValue.Massachusetts:
    case USStateValue.Maryland:
    case USStateValue.Minnesota:
    case USStateValue.Missouri:
    case USStateValue.NewJersey:
    case USStateValue.SouthCarolina:
    case USStateValue.Tennessee:
    case USStateValue.Virginia:
    case USStateValue.Washington:
    case USStateValue.Wisconsin:
      return 3;
    case USStateValue.Arkansas:
    case USStateValue.Connecticut:
    case USStateValue.Iowa:
    case USStateValue.Kansas:
    case USStateValue.Kentucky:
    case USStateValue.Louisiana:
    case USStateValue.Mississippi:
    case USStateValue.Nevada:
    case USStateValue.Oklahoma:
    case USStateValue.Oregon:
    case USStateValue.Utah:
      return 4;
    case USStateValue.Delaware:
    case USStateValue.Idaho:
    case USStateValue.Maine:
    case USStateValue.Montana:
    case USStateValue.NorthDakota:
    case USStateValue.Nebraska:
    case USStateValue.NewHampshire:
    case USStateValue.NewMexico:
    case USStateValue.RhodeIsland:
    case USStateValue.SouthDakota:
    case USStateValue.Vermont:
    case USStateValue.WestVirginia:
    case USStateValue.Wyoming:
    case USTerritoryValue.WashingtonDC:
      return 5;
    case USStateValue.Alaska:
    case USStateValue.Hawaii:
    case USTerritoryValue.AmericanSamoa:
    case USTerritoryValue.Guam:
    case USTerritoryValue.JohnstonAtoll:
    case USTerritoryValue.NorthernMarianaIslands:
    case USTerritoryValue.MidwayAtoll:
    case USTerritoryValue.PanamaCanalZone:
    case USTerritoryValue.PuertoRico:
    case USTerritoryValue.USGovernment:
    case USTerritoryValue.USVirginIslands:
    case USTerritoryValue.WakeIsland:
    case CanadianValue.Alberta:
    case CanadianValue.BritishColumbia:
    case CanadianValue.Manitoba:
    case CanadianValue.NewBrunswick:
    case CanadianValue.NewfoundlandAndLabrador:
    case CanadianValue.NorthwestTerritories:
    case CanadianValue.NovaScotia:
    case CanadianValue.Nunavut:
    case CanadianValue.Ontario:
    case CanadianValue.PrinceEdwardIsland:
    case CanadianValue.Quebec:
    case CanadianValue.Saskatchewan:
    case CanadianValue.Yukon:
    case MexicanValue.Aguascalientes:
    case MexicanValue.BajaCalifornia:
    case MexicanValue.BajaCaliforniaSur:
    case MexicanValue.Chihuahua:
    case MexicanValue.Colima:
    case MexicanValue.Campeche:
    case MexicanValue.Coahuila:
    case MexicanValue.Chiapas:
    case MexicanValue.DistritoFederal:
    case MexicanValue.Durango:
    case MexicanValue.Guerrero:
    case MexicanValue.Guanajuato:
    case MexicanValue.Hidalgo:
    case MexicanValue.Jalisco:
    case MexicanValue.MéxicoState:
    case MexicanValue.Michoacán:
    case MexicanValue.Morelos:
    case MexicanValue.Nayarit:
    case MexicanValue.NuevoLeón:
    case MexicanValue.Oaxaca:
    case MexicanValue.Puebla:
    case MexicanValue.Querétaro:
    case MexicanValue.QuintanaRoo:
    case MexicanValue.Sinaloa:
    case MexicanValue.SanLuisPotosí:
    case MexicanValue.Sonora:
    case MexicanValue.Tabasco:
    case MexicanValue.Tlaxcala:
    case MexicanValue.Tamaulipas:
    case MexicanValue.Veracruz:
    case MexicanValue.Yucatán:
    case MexicanValue.Zacatecas:
      return 10;
    case NativeAmericanValue.AbenakiNation:
    case NativeAmericanValue.AbsenteeShawneeTribe:
    case NativeAmericanValue.AleutCommunity:
    case NativeAmericanValue.ApacheTribe:
    case NativeAmericanValue.BadRiverBandLakeSuperiorChippewa:
    case NativeAmericanValue.BayMillsOjibwe:
    case NativeAmericanValue.BoisForteBandOfChippewa:
    case NativeAmericanValue.BureauOfIndianAffairs:
    case NativeAmericanValue.CaddoNation:
    case NativeAmericanValue.CherokeeNation:
    case NativeAmericanValue.CheyenneArapahoTribes:
    case NativeAmericanValue.CheyenneRiverSioux:
    case NativeAmericanValue.ChickaloonVillage:
    case NativeAmericanValue.ChickasawNation:
    case NativeAmericanValue.ChoctawNation:
    case NativeAmericanValue.CitizenPotawatomiNation:
    case NativeAmericanValue.ColvilleTribe:
    case NativeAmericanValue.ComancheNation:
    case NativeAmericanValue.CrowCreekSioux:
    case NativeAmericanValue.DelawareNation:
    case NativeAmericanValue.DevilsLakeSiouxTribe:
    case NativeAmericanValue.EasternBandOfCherokeeIndians:
    case NativeAmericanValue.EasternShawneeTribe:
    case NativeAmericanValue.FlandreauSanteeSioux:
    case NativeAmericanValue.FondDuLacBandOfLakeSuperiorChippewa:
    case NativeAmericanValue.GoldCreekSusitna:
    case NativeAmericanValue.GrandPortageBandOfLakeSuperiorChippewa:
    case NativeAmericanValue.HoChunkNation:
    case NativeAmericanValue.IowaTribe:
    case NativeAmericanValue.KalispelTribe:
    case NativeAmericanValue.KawNation:
    case NativeAmericanValue.KeetoowahBandOfCherokeeIndians:
    case NativeAmericanValue.KeweenawBayOjibwaTribe:
    case NativeAmericanValue.KickapooTribe:
    case NativeAmericanValue.KiowaTribe:
    case NativeAmericanValue.KnikTribe:
    case NativeAmericanValue.LacCourteOreillesOjibweNation:
    case NativeAmericanValue.LacDuFlambeauOjibweNation:
    case NativeAmericanValue.LeechLakeBandOfOjibwe:
    case NativeAmericanValue.LittleShellPembinaBand:
    case NativeAmericanValue.LowerBruleSioux:
    case NativeAmericanValue.LummiTribe:
    case NativeAmericanValue.MakahIndianNation:
    case NativeAmericanValue.MandanHidatsaAndArikaraNation:
    case NativeAmericanValue.MenomineeNation:
    case NativeAmericanValue.MiamiNation:
    case NativeAmericanValue.MiccosukeeNation:
    case NativeAmericanValue.MilleLacsBandOfOjibwe:
    case NativeAmericanValue.ModocTribe:
    case NativeAmericanValue.MuckleshootTribe:
    case NativeAmericanValue.MuscogeeCreekNation:
    case NativeAmericanValue.NanticokeIndianAssociation:
    case NativeAmericanValue.NativeIndianTribalPlates:
    case NativeAmericanValue.NavajoCodeTalker:
    case NativeAmericanValue.NorthernCherokeeNation:
    case NativeAmericanValue.OglalaSioux:
    case NativeAmericanValue.OneidaNation:
    case NativeAmericanValue.OsageNation:
    case NativeAmericanValue.OtoeMissouriaTribe:
    case NativeAmericanValue.OttawaTribe:
    case NativeAmericanValue.OuachitaWashitaw:
    case NativeAmericanValue.PakawaniNation:
    case NativeAmericanValue.PassamaquoddyTribe:
    case NativeAmericanValue.PawneeNation:
    case NativeAmericanValue.PenobscotNation:
    case NativeAmericanValue.PeoriaNation:
    case NativeAmericanValue.PoncaNation:
    case NativeAmericanValue.PotawatomiPrairieBand:
    case NativeAmericanValue.PuyallupTribe:
    case NativeAmericanValue.QuapawTribe:
    case NativeAmericanValue.QuinaultNation:
    case NativeAmericanValue.RedCliffBandOfLakeSuperiorChippewa:
    case NativeAmericanValue.RedLakeBandOfChippewa:
    case NativeAmericanValue.RosebudSioux:
    case NativeAmericanValue.SacAndFoxNation:
    case NativeAmericanValue.SaginawChippewaTribe:
    case NativeAmericanValue.SeminoleIndians:
    case NativeAmericanValue.SeminoleNation:
    case NativeAmericanValue.SenecaCayugaTribe:
    case NativeAmericanValue.ShawneeTribe:
    case NativeAmericanValue.SissetonWahpetonSioux:
    case NativeAmericanValue.SouthernCherokeeNation:
    case NativeAmericanValue.SouthernUteTribe:
    case NativeAmericanValue.SpiritLakeSiouxTribe:
    case NativeAmericanValue.SpokaneTribe:
    case NativeAmericanValue.StandingRockSioux:
    case NativeAmericanValue.TonkawaTribe:
    case NativeAmericanValue.TribalVehicles:
    case NativeAmericanValue.TulalipTribes:
    case NativeAmericanValue.TurtleMountainChippewa:
    case NativeAmericanValue.UteMountainTribe:
    case NativeAmericanValue.WabanakiTribe:
    case NativeAmericanValue.WashitawOuachita:
    case NativeAmericanValue.WhiteEarthBandOfChippewa:
    case NativeAmericanValue.WichitaTribe:
    case NativeAmericanValue.WyandotteNation:
    case NativeAmericanValue.YakamaNation:
    case NativeAmericanValue.YanktonSiouxTribe:
    case NativeAmericanValue.YsletaDelSurPueblo:
      return 20;
    default:
      return 0;
  }
};
